version: "3.5"

services:
  postgres_db:
    image: postgres:14.4
    restart: on-failure
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: localhost
      POSTGRES_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:${POSTGRES_PORT}/${POSTGRES_DB}
  adminer:
    image: adminer:latest
    restart: on-failure
    ports:
      - 9001:8080
